version: '3.8'

services:
  db:
    image: postgres:13
    container_name: water_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: global_water
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  app:
    build: .
    container_name: water_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: global_water
      DB_USER: postgres
      DB_PASSWORD: root
    volumes:
      - .:/app
    command: >
      sh -c "python load_and_standardize.py &&
             python clean_data.py &&
             python transform_data.py &&
             python merge_data.py &&
             python calculate_indices.py &&
             python load_to_postgres.py"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  postgres_data:
  grafana_data: